version: "3.8"

services:
  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - auth_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: .
    container_name: auth-service
    restart: always
    depends_on:
      - auth-db
    ports:
      - "4665:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: auth-db
      DB_NAME: authdb
      DB_USER: user
      DB_PASSWORD: password

volumes:
  auth_data:
